{% set name = "hydra-core" %}
{% set version = "1.4.0.dev1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hydra_core-{{ version }}.tar.gz
  sha256: 664e6755ea78f070b403df911fc460ea3464fdc59bd03affc0d6ffef9dd53221

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} setup.py antlr
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - antlr ==4.11.*
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - omegaconf >=2.4.0.dev3
    - packaging

test:
  imports:
    - hydra
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - hydra
    - tests
  commands:
    - pytest -v -W ignore::DeprecationWarning tests/

about:
  home: https://hydra.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for elegantly configuring complex applications
  doc_url: https://hydra.cc/docs/intro/
  dev_url: https://github.com/facebookresearch/hydra

extra:
  recipe-maintainers:
    - mdraw
    - benjaminrwilson
