{% set name = "hydra-core" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/hydra/archive/v{{ version }}.tar.gz
  sha256: e8d07826e5da25c26b4a1a701817bf7afaa5375a90a4cb229c111d128de56961

build:
  noarch: python
  number: 0
  script_env:
   - HYDRA_FULL_ERROR=1
  script:
    - {{ PYTHON }} setup.py antlr
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - antlr ==4.8
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - omegaconf ==2.1.*
    - antlr-python-runtime ==4.8

    # importlib_resources is only needed for Python 3.9, but can't
    # specify that with `noarch`
    - importlib_resources

test:
  imports:
    - hydra
  requires:
    - pytest
  source_files:
    - hydra
    - tests
    - examples
    - pytest.ini
    - ATTRIBUTION
  commands:
    - pytest -v tests/

about:
  home: https://hydra.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for elegantly configuring complex applications
  doc_url: https://hydra.cc/docs/intro/
  dev_url: https://github.com/facebookresearch/hydra

extra:
  recipe-maintainers:
    - mdraw
    - benjaminrwilson
