{% set name = "hydra-core" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/hydra/archive/v{{ version }}.tar.gz
  sha256: 97446903f8ede408323f2da9f1f047538ecbee64340a83fa9f8d140f22d2aa0c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - omegaconf >=1.4,<1.5
    - typing-extensions

test:
  imports:
    - hydra
  requires:
    - pytest
  source_files:
    - hydra
    - tests
    - examples
    - pytest.ini
    - ATTRIBUTION
  commands:
    - pytest

about:
  home: https://hydra.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for elegantly configuring complex applications
  doc_url: https://hydra.cc/docs/intro/
  dev_url: https://github.com/facebookresearch/hydra

extra:
  recipe-maintainers:
    - mdraw
