{% set name = "hydra-core" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/hydra/archive/v{{ version }}.tar.gz
  sha256: 05de1c23af2df0e4bfe00fddb51d585d387e6389a3b1d3bb91dda6e791e2cf45

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9
    - omegaconf >=2.0.2
    - antlr-python-runtime ==4.8

test:
  imports:
    - hydra
  requires:
    - pytest
  source_files:
    - hydra
    - tests
    - examples
    - pytest.ini
    - ATTRIBUTION
  commands:
    - pytest

about:
  home: https://hydra.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for elegantly configuring complex applications
  doc_url: https://hydra.cc/docs/intro/
  dev_url: https://github.com/facebookresearch/hydra

extra:
  recipe-maintainers:
    - mdraw
